include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    # prefer_single_quotes: true
    # use_build_context_synchronously: false
    # library_private_types_in_public_api: false
    # prefer_const_constructors: false
# https://dart.dev/guides/language/analysis-options