name: smart_parents
description: Final year project 'Smart Parents'.
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

# flutter pub upgrade --major-versions
# flutter pub outdated
dependencies:
  flutter:
    sdk: flutter

  # firebase_storage: ^11.0.14
  # firebase_messaging: ^14.2.5
  # flutter_local_notifications: ^13.0.0

  flutter_datetime_picker: ^1.5.1
  google_nav_bar: ^5.0.6
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  shared_preferences: ^2.0.18
  focused_menu: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  # android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/Final.png"
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
  # flutter pub get
  # flutter pub run flutter_launcher_icons

flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/images/
   - assets/Photo/